### ISSUE TITLE
Make bestMatches case insensitive

### ISSUE THREAD

**Issue by philogit** [snowgoon88/TW5-extendedit#1]
Thank you for your great work on this plugin. One suggestion: Make it so that the completion object returns results regardless of the case (upper or lower) of the user's input.

Changing `regpat.test( listChoice[i] )` to `regpat.test( listChoice[i].toLowerCase() )` within _completion.js_ changed the behavior for me.

Thanks!

**Comment by snowgoon88** [comment]
Yes. I'll add some configuration in next release with case sensitive/insensitive choice.
My option is to change 
`var regpat = RegExp( this._regExpEscape(pattern));` 
to 
`var regpat = RegExp( this._regExpEscape(pattern), "i");`
so as to have a case insensitive search.

**Comment by philogit** [comment]
That works perfectly. Cheers!
