### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by pmario** [snowgoon88/TW5-extendedit#12]
Hi, ... Nice plugin!

But your licensing file is missing. So the plugin can't be used, if the TiddlyWiki is accessible from the web.

**Comment by pmario** [comment]
Some suggestions: 

 - If you think your plugin should be part of the core some time, [BSD-3-clause](https://opensource.org/licenses/BSD-3-Clause) is an option, since TW uses it. So no compatibility problems
 - If you don't care: [MIT](https://opensource.org/licenses/MIT) may be an option, since it is even more liberal than BSD. 
 - If you want to use more restrictions, a [CC-type](https://creativecommons.org/) license would be an option too. ...

**Comment by snowgoon88** [comment]
Sorry, took a long time to answer/react.
It might be nice for this plugin to be intergrated in the core, why not.
I usually do not care about licensing, but if it is required from TW5, I'll have a look and learn.
So BSD-3-clause is required to be part of the core or MIT is enough ?
Thanks.

**Comment by pmario** [comment]
close because it's MIT now. thx.
