### ISSUE TITLE
Cursor Position not calculating as expected when using comptext widget

### ISSUE THREAD

**Issue by RK-Shaw** [snowgoon88/TW5-extendedit#16]
Hello,

I I have found a bug with the cursor position that I am unable to fix. When housing an <$edit-comptext> widget inside of any HTML table, the popup element to select the desired option is rendering in the corner of the tiddler. This can be replicated with the below code:

```
<$list filter="[{!!title}addprefix[test]]">
<table><$edit-comptext field="leader" placeholder="Leader of this org" />
</table>
</$list>
```

Unclear as to what the solution here would be. Thanks for the good work, this plugin is still one of my favorites :)

**Comment by snowgoon88** [comment]
Hello. Ok.....
Hmm, first I am not very fluent with the TW widgets by themselves (the <$things...>). So, I have copied your twtext inside a TW (version 5.1.11) and indeed, I get a tiddler with an input field where the popup behave "strangely".

But, when I look at the DOM, in a "regular" Tiddler, in edit mode, the editor is a 
`<textarea class="tc-edit-texteditor" style="height: 100px;">text</textarea>`
whereas in using your example, the input element of the tiddler is a 
`<input type="text">`

So I do not know what is exactly behind the <$edit-comptext ... /> tw_widget, but it does not behave as a "classical tiddler editor". Besides, INPUT element is very different from TEXTAREA (one line max vs multilines)...

To be sure that I did things right, here is a snapshot of a tiddler Bug2 with the code you gave me. Is this correct ?
![bug2](https://user-images.githubusercontent.com/1554516/84443360-bc486680-ac3f-11ea-8d69-12b96add9dfb.png)

The module to compute the caret position (that I did not write) works like this : it create a dummy textarea, set it to the same style than the original textarea (of the editor), paste the current text in it and, from the size of this dummu one-line textarea, deduce the actuai position of the carret in the original textarea.
With an input elements, I do not know what happens...

**Comment by RK-Shaw** [comment]
Hey, thanks for checking this. Let me show what this looks like in preview mode with screenshots. I am somewhat ignorant of how the widgets work specifically, but as I understand the plugin generates the ability to use $edit-comptext as opposed to $edit-text which is the normal mode of editing.

the issue only occurs when the widget is wrapped in an HTML attribute, like a table. See the below.

In this image, you can see the HTML table (top) editing the field is causing the placement of the input box to appear in the top left corner.
![image](https://user-images.githubusercontent.com/47098368/84688219-f9954880-af0c-11ea-9b30-0117018280e8.png)

Without the HTML attribute wrapping, the cursor position calculates as expected:
![image](https://user-images.githubusercontent.com/47098368/84688769-e8007080-af0d-11ea-9efa-a3145f7780fc.png)

I may have a friend who is more JS literate than I check to see if he can sus why the element is calculating incorrectly as well. Here's the code snippet:

```
<$list filter="[{!!title}addprefix[test]]">
<table><$edit-comptext field="field-1" placeholder="field 1" />
</table>
</$list>
<$list filter="[{!!title}addprefix[test]]">
<$edit-comptext field="field-2" placeholder="field 2" />
</$list>
```

*Note the dom explorer is not giving me much info besides where the calculated position is ending up. I can't determine why the position script is calculating like that so far. Trying to debug.

![image](https://user-images.githubusercontent.com/47098368/84689535-1e8abb00-af0f-11ea-8b76-40c0ac934f58.png)

![image](https://user-images.githubusercontent.com/47098368/84689548-234f6f00-af0f-11ea-9d5a-b72ca339a48f.png)

**Comment by saqimtiaz** [comment]
@RK-Shaw Try giving your table `position:relative` (via class + CSS or inline style)

**Comment by snowgoon88** [comment]
@saqimtiaz : thanks for the tip. Works great

If I use the following code, it works
```
<$list filter="[{!!title}addprefix[test]]">
<table style="position:relative">
<$edit-comptext field="field-1" placeholder="field 1" />
</table>
</$list>
<$list filter="[{!!title}addprefix[test]]">
<$edit-comptext field="field-2" placeholder="field 2" />
</$list>
```

![screen_tw](https://user-images.githubusercontent.com/1554516/84698899-e310e080-af50-11ea-8c0e-353b2c5e5e6b.png)


If I understand properly, the reason for this is that the popup element has `position:absolute` and so needs an "anchor" to position itself. And adding the `position:relative` to the table element makes it a proper anchor. Nice.

(I have so much to learn....)

**Comment by RK-Shaw** [comment]
awesome! that works as stated, time to go about applying that element to my various table classes in my stylesheet!

Cheers,
-RKS
