### ISSUE TITLE
Plugin does not prevent propagation of event from framed editor

### ISSUE THREAD

**Issue by saqimtiaz** [snowgoon88/TW5-extendedit#18]
keydown events - such as enter to select an autocomplete entry - are still propagated to the main document from the framed editor (which is inside an iframe). This is due to [some special handling of events inside the iframe](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/editor/factory.js#L289) in TW, by which events from the iframe are propagated to the parent document. This causes clashes with other plugins that also react to keyboard events.

I will submit a pull request in a few days that works around this, so that events are only propagated further if not handled by the autocomplete.

**Comment by snowgoon88** [comment]
Oh, ok. I'll let you explore that...
BTW, would you like to be a collaborator on this  project ?
Snow

**Comment by saqimtiaz** [comment]
If that would be helpful, sure you can add me as a collaborator. I don't expect to work on it more after this bug fix unless something else comes up.

**Comment by snowgoon88** [comment]
Sorry, I was on vacation. I'll set you up as collaborator.
Snow

**Comment by snowgoon88** [comment]
I guess last commit (721b122d502ddb15b1ac6b20d71770cf5c9759c3) fixed that.
We could close, no ?

**Comment by saqimtiaz** [comment]
Yes, I should have closed it.
