### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by adithya-badidey** [snowgoon88/TW5-extendedit#19]
Got this error when normally using TW (with comptext). The TextArea was not empty.

```
Uncaught TypeError: Cannot read property 'start' of undefined
    at Completion.handleKeyup ($:/plugins/snowgoon88/edit-comptext/completion.js:484)
    at HTMLTextAreaElement.handler ($:/core/modules/utils/dom.js:207)
```

**Comment by snowgoon88** [comment]
Hello,

I do not have a lot of details to work with...
What version of edit-comptext are you using ? and of TW ?
Can you describe what you were doing when it happened ? Remember if some options were listed in the popup window ?

It seems to that you hit 'ENTER', with (or without ?) a valid choice but the "search pattern" (i.e the portion of text that is used to search for options was not existant. Did you moved the cursor with the mouse ? With the arrow keys ? Something else.

I need to reproduce the bug to better understand in fact.

Alain

**Comment by adithya-badidey** [comment]
Hey Alain, 

Sorry for not giving more details the first time around.
I have stopped using comptext since I switched to Codemirror so I have not encountered this bug recently and the details are a bit fuzzy. I will open this issue again if I run across it.

Adithya.
