### ISSUE TITLE
Add ul to popupNode

### ISSUE THREAD

**Issue by philogit** [snowgoon88/TW5-extendedit#2]
I noticed that the li results displayed within the popupNode lack a ul container which throws the bullets outside the container (at least on Firefox).

Related: For a cleaner look, should bullets be droppped the from li styling?

**Comment by snowgoon88** [comment]
Yep, Absolutely. I'll correct this by adding an `<ul>` with `list-style-type: none;`.
Don't know why the bullet disapear when the item is selected though...

And, also, I've messed up my CSS tiddler.... o:( Sorry. I'll fix this at once.

**Comment by snowgoon88** [comment]
For now, I'm still going without `<ul>`. We'll see.
