### ISSUE TITLE
Using the TAB key

### ISSUE THREAD

**Issue by dbobak** [snowgoon88/TW5-extendedit#21]
It is not possible to use a TAB key to insert tabulation in the editor window; the cursor is moved to the next control. Would it be possible to add the posibility of using the TAB key?

best,
Darek

**Comment by saqimtiaz** [comment]
@dbobak This is unrelated to the purpose of the plugin, which is to provide link autocompletion. This plugin extends the default TiddlyWiki editor. If that editor is extended by another plugin or the TiddlyWiki core itself, to support insert TAB characters, that support will become available in this plugin as well.
