### ISSUE TITLE
Complete onClick / onTouch

### ISSUE THREAD

**Issue by rrrnld** [snowgoon88/TW5-extendedit#23]
Hi and first of all thanks for the nice plugin. :) Works great for my case!

One question: Is it possible to finish the completion `onClick` or `onTouch`? At the moment I have to select a completion entry via arrow keys if I understand this correctly and this makes it unsuitable for mobile devices (which is a pity because otherwise it seems to work great).

Thanks again.

**Comment by snowgoon88** [comment]
Hi,
ok, I understand the motivation (I'm used to keyboard-only/mainly settings, so...)
I'll have a look and see how to add this Click and/or Touch event.

**Comment by snowgoon88** [comment]
Hello,
you can now click/touch a completion proposal to insert it into the tiddler.
Should be working...

I'll close this issue in a few days if no bugs...
Snow

**Comment by rrrnld** [comment]
Thanks for implementing this! I added some CSS to provide visual feedback that there's actually some mouse interaction possible in #26.

**Comment by snowgoon88** [comment]
Thanks, as I commented on pull request #26, It might need some more work for a seamless integration.

**Comment by snowgoon88** [comment]
I have added a "mouse_hover" callback in branch mouse_integration  [6a5b01db2cdc5133943f81ea75dcba6e8072aace and  e09327e39d33750d60d8b11f0c22b4d3cee9c732]
I removed the CSS modification as "selected" status is now only governed by keyboard XOR mouse (not both).

Better ?
Or you like better your way as on #26 ?

**Comment by saqimtiaz** [comment]
Can we make a release for a new version soon?

**Comment by snowgoon88** [comment]
Yes. I waited for a answer by heyarne, but...
So, a new release is done.

**Comment by saqimtiaz** [comment]
Thank you @snowgoon88
