### ISSUE TITLE
Pb Mac OS 10.6 with Firefox et Chrome

### ISSUE THREAD

**Issue by snowgoon88** [snowgoon88/TW5-extendedit#5]
From :Sylvain Naudin silvynATgmailDOTcom

**Comment by silvyn** [comment]
Hi :)
I'll retry because on Gnu/Linux it doesn't work at my first try.
I use to copy/paste [[ and don't type character.. If i type it, it's working on my Fedora.

**Comment by snowgoon88** [comment]
Hello,

I tried the actuel version (0.6.1) on a Mac with Firefox, Safari and
Chrome. It is working fine for me : if I type '[[', I trigger the
completion mecanism...
So I do not know what's going wrong with your setup.

Alain

**Comment by silvyn** [comment]
You can close it @snowgoon88, like I said, I was trying with copy/paste of double brackets and typing. It doesn't work after.
But if I type Alt + Shift + ( twice, and start with existing title tiddler, I've the popup.
