### ISSUE TITLE
Support for languages having complex input methods

### ISSUE THREAD

**Issue by zimiarh** [snowgoon88/TW5-extendedit#9]
Hi! Thanks a lot for developing this cool plugin. I tried it out a little and feel that it is a must have for anyone who is as lazy as me.

However, I also noticed that this plugin is not quite responsive with certain languages, such as Chinese and Japanese. To be more specific, autocompletion candidates almost never show up when I try to type names of tiddlers in these two languages. If I copy part of the desired tilddler name, typing the autocompletion triggering pattern, and paste the copied texts, the autocompletion window might show up (although the probability is quite small).

For Japanese users, luckily enough, pressing the key combination `ctrl` + `space` can invoke the autocompletion window manually. For Chinese users however, doing so does not work because such key combination usually is intercepted by the input method to switch input modes (on Win 10, it locks/unlocks the key board to input English alphabets instead of Chinese).

I am not quite sure about the root cause of this issue because I have not read the source code yet. My guess is that it cannot handle the texts output of an input method that generating a character by collecting and combining multiple key strokes. This is the common point of the two languages that the plugin fails on.

**Comment by zimiarh** [comment]
It turns out that for users typing Chinese on Win 10, pressing `control` + `shift` + `space` would circumvent the problem and successfully invokes the completion candidates window because the extra `shift` key prevents the input method from responding the key combination and consuming the key press event.

That being said, I still add a tiny feature that allows users to define their own autocompletion triggering key combination in the configuration tiddler. I would like to make a pull request and will do any refinement or git beautifications (if necessary) if @snowgoon88  feels its okay to accept this feature.

**Comment by snowgoon88** [comment]
Hello,
sadly, I know nothing about using complex input methods. So I might not be very helpfull...
This being said, any pull request that seems interesting and does not break the basic behavior will be accepted, of course.

I must add that, in the new version of TiddlyWiki (5.1.15), `ctrl + space` does not work anymore. I think it might be intercepted earlier by TW.

Snow.

**Comment by zimiarh** [comment]
Hi,
I opened a pull request that adds the feature I mentioned before. However, I am pretty bad at naming and am a super newbie at JavaScript so please feel free to tell me where to change!
